# Generated by Django 4.1.2 on 2024-07-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaZapatillasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
