# Generated by Django 4.1.2 on 2024-07-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaZapatillasApp', '0002_alter_cliente_apellido_materno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapatilla',
            name='rut',
        ),
    ]
