# Generated by Django 4.1.2 on 2024-07-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaZapatillasApp', '0003_remove_zapatilla_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_zapatilla',
            name='id_marca',
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='marca',
            field=models.CharField(default='Sin especificar', max_length=20),
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='modelo',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo_zapatilla',
        ),
    ]
