# Generated by Django 4.1.2 on 2024-07-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaZapatillasApp', '0004_remove_modelo_zapatilla_id_marca_zapatilla_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='talla',
            field=models.IntegerField(null=True),
        ),
    ]
